[package]
name = "modelutils_rs"
version = "0.1.0"
edition = "2021"
authors = ["Sean McConnachie <seanjulian.mcc@gmail.com>"]

[dependencies]
tobj = "4.0.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
